source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '9.0'
use_frameworks!

def default_pods
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
end

# Developement
target 'ProjectName' do

  default_pods

end
